// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uklatynnbocahgmibnyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrbGF0eW5uYm9jYWhnbWlibnlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MzI2MjEsImV4cCI6MjA2ODMwODYyMX0.j3vnu77z6QcZkeRI8JyQuVd_ExiDQw1tVXGyUL5JzwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});